export const ASSOCIATIONS = [
    '3x3 Proteam (3x3 Proteam)',
    '7a+',
    'Alternatives écologiques engagées et soutenables (Alte²s)',
    'Année du Tigre (AdT)',
    'ARGIL (K-Fêt)',
    'Ass. Chercheurs Elèves-Ingénieurs Marocains INSA (ACEIMI)',
    'Association Biosciences INSA Lyon (ABIL)',
    'Association des Alternants INSA Lyon (INSALTERNANT)',
    "Association des élèves de GEn de l'INSA de Lyon (AGENIL)",
    'Association des Élèves de génie Electrique (ADEGE)',
    'Association des Elèves des INSA (AEI)',
    'Association des Élèves du Département Informatique (AEDI)',
    'Association des Elus aux Conseils de l’INSA Lyon (ADECIL)',
    "Association des Jongleurs de l'INSA de Lyon (AJIL)",
    "Association des Vietnamiens de l'INSA (AVI)",
    'Association du Festival Un Doua de Jazz (UDDJ)',
    'Association Génie Industriel (AGI)',
    "Association Musicale de l'INSA (AMI)",
    "Association SCAN de l'INSA de Lyon (ASIL)",
    'Association Sportive Football INSA Lyon (AS Foot INSA Lyon)',
    'Association Télécommunication Usages et Services (ASTUS)',
    'Basket INSA Club (BASIC)',
    'Board of European Students of Technology Lyon (BEST Lyon)',
    'Boards of Mangroove (BoM)',
    "Bob'INSA Loisirs",
    'Bureau Amerinsa (AMER)',
    'Bureau des Élèves (BdE INSA Lyon)',
    'CAP Génie Civil Urbanisme (CAP GCU)',
    "Chap's ANGELS",
    'Ciné - La Mouette (La Mouette)',
    'CLES-FACIL',
    'Club BD Manga Loisirs',
    "Club d'Œnologie - INSA Lyon (Club œno) Loisirs",
    "Club des 24 heures de l'INSA (24h de l'INSA)",
    'Club INSA Athlétisme (CIA)',
    'Club Jeux & Imaginaire (CLUJI) Loisirs',
    'Club Montagne INSA (Club Montagne)',
    'Club Rock',
    'Clubelek',
    "Cod'INSA",
    'Commission de Gestion de la Rotonde (CGR)',
    'Cultures et Identités Européennes (CUID)',
    'Elevate (Elevate)',
    "Ensemble Vocal de l'INSA (EVI)",
    'ESTIEM LG Lyon (ESTIEM Lyon)',
    'ETIC INSA Technologies (ETIC)',
    'Europea',
    'Exit',
    'Forum Organisation (FO)',
    'GAIA',
    'Gatsun (Gatsun Records)',
    "Graines d'Images (GI)",
    'Handball INSA club (HIC)',
    'Handizgoud',
    'Harmonie',
    'IACES-Lyon (IACES Lyon)',
    'InciDanse (AS Danse)',
    'Ingénieur.e.s Sans Frontières INSA Lyon (ISF)',
    'INSA Alternants Plasturgistes (INSAAP)',
    'INSA Esport (INSA Esport)',
    'INSA on ICE',
    'INSA Sailing Club (ISC)',
    'INSA Talks (TEDxINSA)',
    'INSAlgo',
    'INSAquatic',
    'InSecurity',
    'K-Le Son (KLS)',
    'Karnaval Humanitaire (Karna)',
    'Kaz Kréyol',
    'Kryptosphere INSA Lyon (KS INSA)',
    "KWANZA'A",
    "L'ALIR Loisirs",
    "L'ART DE LA SCENE (L'Art-Scène)",
    "La Band'As",
    'La Semaine Asiatique (SA)',
    'Le Culinarium',
    'Le Doua Vert (Doua Vert (DV))',
    'Les Bikers',
    'Les Sang-Culottes',
    'Lézarts',
    'Ligue des Fadas de Handball Etudiantes (LFHé)',
    'Lorelei',
    'Matériaux INSA Association (MATIASS)',
    'MECASPORT INSA LYON (Mecasport)',
    'Objectif 21',
    'Orchestre Symphonique Insa Universités (OSIU)',
    "Pétanqu'INSA Club (PETIC)",
    "Plast'Avenir",
    'Projeto Conexão (Conexao)',
    'PROMECA (PROMECA)',
    'Proméca (Proméca)',
    'Proto INSA Club (PIC)',
    'Raid Dahu (Raid Dahu)',
    'Raquettes INSA Club (RIC)',
    'Rythmes Aéro Gym Danse Association (RAGDA)',
    'Service Informatique Associatif (SIA)',
    "Ski Club de l'INSA (Ski Club)",
    'Solidaction',
    "Sports de Kombat de l'INSA LYON (SKIL (ancien ASCIL))",
    'Standard Latino Insa Dance Entertainement (Slide)',
    "Troupe Théâtrale de l'INSA (TTI)",
    'VAMOS (Vamos)',
    'Wing-Over (Wing-Over)',
];
