export const ASSOCIATIONS = [
    "La Band'As Animation du campus",
    'VAMOS (Vamos) Association de département',
    'Association Génie Industriel (AGI) Association de département',
    'Les Bikers Humanitaire et social',
    'Kaz Kréyol Cultures internationales',
    'Proméca (Proméca) Association de département',
    "L'ALIR Loisirs",
    'Harmonie Arts et spectacles',
    'Alternatives écologiques engagées et soutenables (Alte²s) Humanitaire et social',
    "Association des Vietnamiens de l'INSA (AVI) Cultures internationales",
    'Le Culinarium Humanitaire et social',
    'Basket INSA Club (BASIC) Sports',
    'Proto INSA Club (PIC) Sciences et Techniques',
    'INSA Sailing Club (ISC) Sports',
    'Wing-Over (Wing-Over) Sports',
    'ARGIL (K-Fêt) Animation du campus',
    "Association des Jongleurs de l'INSA de Lyon (AJIL) Arts et spectacles",
    'La Semaine Asiatique (SA) Cultures internationales',
    "Ski Club de l'INSA (Ski Club) Sports",
    'CLES-FACIL Sciences et Techniques',
    'Bureau des Élèves (BdE INSA Lyon) Animation du campus',
    'Matériaux INSA Association (MATIASS) Association de département',
    'Handizgoud Humanitaire et social',
    'GAIA Association de département',
    'InSecurity Sciences et Techniques',
    "Ensemble Vocal de l'INSA (EVI) Arts et spectacles",
    'Solidaction Humanitaire et social',
    'Association Sportive Football INSA Lyon (AS Foot INSA Lyon) Sports',
    '7a+ Sports',
    'Cultures et Identités Européennes (CUID) Cultures internationales',
    'Handball INSA club (HIC) Sports',
    'Association des Elèves des INSA (AEI) Animation du campus',
    'INSA on ICE Sports',
    'Association Biosciences INSA Lyon (ABIL) Association de département',
    'Board of European Students of Technology Lyon (BEST Lyon) Cultures internationales',
    'Club Rock Arts et spectacles',
    'Raid Dahu (Raid Dahu) Sports',
    'Clubelek Sciences et Techniques',
    "Plast'Avenir Association de département",
    "Bob'INSA Loisirs",
    "Cod'INSA Sciences et Techniques",
    'Club BD Manga Loisirs',
    'Gatsun (Gatsun Records) Animation du campus',
    "Association des élèves de GEn de l'INSA de Lyon (AGENIL) Association de département",
    'Lorelei Cultures internationales',
    'Ligue des Fadas de Handball Etudiantes (LFHé) Sports',
    'Club INSA Athlétisme (CIA) Sports',
    'Lézarts Arts et spectacles',
    'MECASPORT INSA LYON (Mecasport) Sciences et Techniques',
    'Objectif 21 Humanitaire et social',
    'K-Le Son (KLS) Animation du campus',
    'Projeto Conexão (Conexao) Humanitaire et social',
    'INSA Talks (TEDxINSA) Animation du campus',
    'Association des Elus aux Conseils de l’INSA Lyon (ADECIL) Animation du campus',
    'Elevate (Elevate) Humanitaire et social',
    "Association Musicale de l'INSA (AMI) Arts et spectacles",
    'InciDanse (AS Danse) Sports',
    'Kryptosphere INSA Lyon (KS INSA) Sciences et Techniques',
    'Raquettes INSA Club (RIC) Sports',
    'Association des Élèves de génie Electrique (ADEGE) Association de département',
    "Pétanqu'INSA Club (PETIC) Sports",
    "Sports de Kombat de l'INSA LYON (SKIL (ancien ASCIL)) Sports",
    'Bureau Amerinsa (AMER) Association de département',
    '3x3 Proteam (3x3 Proteam) Sports',
    'Karnaval Humanitaire (Karna) Animation du campus',
    'Europea Association de département',
    'Club Montagne INSA (Club Montagne) Sports',
    'CAP Génie Civil Urbanisme (CAP GCU) Association de département',
    'Association Télécommunication Usages et Services (ASTUS) Association de département',
    'Ass. Chercheurs Elèves-Ingénieurs Marocains INSA (ACEIMI) Cultures internationales',
    'Association du Festival Un Doua de Jazz (UDDJ) Arts et spectacles',
    "L'ART DE LA SCENE (L'Art-Scène) Arts et spectacles",
    "Club d'Œnologie - INSA Lyon (Club œno) Loisirs",
    'INSA Esport (INSA Esport) Sports',
    'INSA Alternants Plasturgistes (INSAAP) Association de département',
    'Ingénieur.e.s Sans Frontières INSA Lyon (ISF) Humanitaire et social',
    "KWANZA'A Cultures internationales",
    'Le Doua Vert (Doua Vert (DV)) Humanitaire et social',
    'Commission de Gestion de la Rotonde (CGR) Arts et spectacles',
    'Forum Organisation (FO) Animation du campus',
    'Rythmes Aéro Gym Danse Association (RAGDA) Arts et spectacles',
    'ESTIEM LG Lyon (ESTIEM Lyon) Cultures internationales',
    'INSAlgo Sciences et Techniques',
    'Club Jeux & Imaginaire (CLUJI) Loisirs',
    'PROMECA (PROMECA) Association de département',
    'Orchestre Symphonique Insa Universités (OSIU) Arts et spectacles',
    "Graines d'Images (GI) Arts et spectacles",
    "Troupe Théâtrale de l'INSA (TTI) Arts et spectacles",
    "Chap's ANGELS Sports",
    'Année du Tigre (AdT) Association de département',
    'Association des Élèves du Département Informatique (AEDI) Association de département',
    'Standard Latino Insa Dance Entertainement (Slide) Arts et spectacles',
    'Les Sang-Culottes Humanitaire et social',
    'Exit Humanitaire et social',
    'Association des Alternants INSA Lyon (INSALTERNANT) Association de département',
    'Service Informatique Associatif (SIA) Sciences et Techniques',
    "Club des 24 heures de l'INSA (24h de l'INSA) Animation du campus",
    'INSAquatic Sports',
    "Association SCAN de l'INSA de Lyon (ASIL) Association de département",
    'Ciné - La Mouette (La Mouette) Arts et spectacles',
    'Boards of Mangroove (BoM) Sports',
    'IACES-Lyon (IACES Lyon) Association de département',
    'ETIC INSA Technologies (ETIC) Sciences et Techniques',
];
