export const PROGRAMS = {
    fimi_classique: 'FIMI FILIÈRE CLASSIQUE',
    fimi_ae2: "ANNÉE D'ÉCHANGE À L'ÉTRANGER (AE2)",
    fimi_danse: 'FIMI "DANSE-ÉTUDES"',
    fimi_cinema: 'FIMI "CINÉMA-ÉTUDES"',
    fimi_musique: 'FIMI "MUSIQUE-ÉTUDES"',
    fimi_arts: 'FIMI "ARTS-PLASTIQUES-ÉTUDES"',
    fimi_theatre: 'FIMI "THÉÂTRE-ÉTUDES"',
    fimi_eurinsa: 'FIMI EURINSA',
    fimi_amerinsa: 'FIMI AMERINSA',
    fimi_asinsa: 'FIMI ASINSA',
    fimi_scan: 'FIMI SCAN',
    fimi_insavenir: "FIMI FILIÈRE INS'AVENIR",
    fimi_sport: 'FIMI SPORT DE HAUT NIVEAU',
    fi2e_ergo: 'BIOTECHNOLOGIES ET BIOINFORMATIQUE',
    fi2e_aero: 'GÉNIE ÉLECTRIQUE',
    fi2e_bio: 'GÉNIE INDUSTRIEL',
    fi2e_chim: 'GÉNIE CIVIL ET GÉNIE URBAIN',
    fi2e_civ: 'GÉNIE ÉNERGÉTIQUE ET GÉNIE DE L’ENVIRONNEMENT',
    fi2e_mat: 'INFORMATIQUE',
    fi2e_ele: 'GÉNIE MÉCANIQUE',
    fi2e_eners: 'MATÉRIAUX (SGM)',
    fi2e_ind: 'TÉLÉCOMMUNICATIONS, SERVICES & USAGES',
    mri_acous: 'Acoustique',
    mri_micetnano: 'MICRO ET NANOTECHNOLOGIES',
    mesp_environ: "MANAGER DE L’ENVIRONNEMENT ET DE L'ECO-EFFICACITÉ",
    mesp_cybersecurite: 'CYBERSÉCURITÉ DU NUMÉRIQUE',
    mesp_gi: 'MANAGER EN GÉNIE INDUSTRIEL',
    mesp_teleco_reseaux: 'INFORMATIQUE, SI, TÉLÉCOMS ET RÉSEAUX',
    mesp_vehicules: 'EXPERT EN VÉHICULES ÉLECTRIFIÉS',
    mesp_gi_maroc: 'MANAGER EN GÉNIE INDUSTRIEL (MAROC)',
    other_doct: 'FORMATION DOCTORALE',
    bacc_ib: 'INTERNATIONAL BACHELOR',
    bacc_assist:
        'BACHELOR ASSISTANT INGÉNIEUR\nMUTATIONS INDUSTRIELLES ET TECHNOLOGIQUES',
    other_spec: 'Ingénieur de spécialisation pour une Industrie ',
    appr_gmppa: 'GÉNIE MÉCANIQUE PROCÉDÉS POLYMÈRES AVANCÉS (GMPPA)',
    appr_gmcip: 'GÉNIE MÉCANIQUE CONCEPTION INNOVATION PRODUITS',
    appr_elec_altern: 'GÉNIE ÉLECTRIQUE EN ALTERNANCE',
    appr_teleco: 'TÉLÉCOMMUNICATIONS, SERVICES & USAGES',
    appr_ifa: 'IFA – INFORMATIQUE, FILIÈRE PAR APPRENTISSAGE',
    form_insavalor: 'FORMATION INSAVALOR',
    form_cont: 'FORMATION CONTINUE',
};

export const PROGRAMS_ARRAY = Object.entries(PROGRAMS).map(([id, name]) => ({
    id,
    name,
}));

export const PROGRAMS_CATEGORY = {
    fimi: "Formation Initiale aux Métiers d'Ingénieur (FIMI)",
    fi2e: 'Formation Ingénieur second cycle',
    mri: 'Master Recherche International',
    mesp: 'Mastère Spécialisé',
    bacc: 'Bachelor',
    appr: 'Ingénieur par apprentissage',
    form: 'Formation Continue',
    other: 'Autres',
};
